#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

$app = new Silex\Application();

require __DIR__ . '/resources/config/config.php';
require __DIR__ . '/resources/bootstrap.php';

$console = require __DIR__ . '/resources/console.php';
$console->run();
